source 'https://rubygems.org'

gem 'selenium-webdriver', '~> 2.53.4'
gem 'parsefile'
gem 'dircrawl'
gem 'emailparser'
gem 'docsplit'
gem 'curb'
gem 'pdftotext'
gem 'mimemagic'
gem 'harvesterreporter'
